spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.291c4f48aec23d1e
            client-secret: 935988895763a836f9213f3471d3bab26a9cbf5a
  data:
    cassandra:
      keyspace-name: main
      #      username: yMenHwsUdhpZwtwLYRXRuYZD
      #      password: 9SwOEdrSAqStQNZ.-W-KYERH3DxWf6xPX40JjnaBHLvbAym+c,j9XDKMYMkPfE3-y_C4N3qA5qW5HyXctuj1nZeTD+Ltg+XZP9Pe4.nwEYGxROgbaGGlaAjcpZu+llmE
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
      contact-points: 127.0.0.1
      port: 9042

cover:
  large:
    url: https://covers.openlibrary.org/b/id/{id}-L.jpg
  medium:
    url: https://covers.openlibrary.org/b/id/{id}-M.jpg

datastax.astra:
  secure-connect-bundle: secure-connect.zip

#astra.db:
#  id: 873756b6-13db-4b1e-9685-8aad64089420
#  region: us-east1
#  keyspace: main
#  application.token: AstraCS:yMenHwsUdhpZwtwLYRXRuYZD:a4a4ae04651e51f9ec93efdd8961d330dce4890b8bf5a92b7b9cbc0c723d7c48